BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS      += "qti-core"
BBFILE_PRIORITY_qti-core = "12"
BBFILE_PATTERN_qti-core := "^${LAYERDIR}/"

LAYERSERIES_COMPAT_qti-core = "thud dunfell"

BBFILES += "${LAYERDIR}/recipes/*/*.bb \
            ${LAYERDIR}/recipes/*/*.bbappend \
            ${LAYERDIR}/recipes-products/images/*.bbappend"
